services:
  postgres:
    image: 'postgres:latest'
    container_name: 'taskzs'
    environment:
      - 'POSTGRES_DB=taskzs'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data